### ISSUE TITLE
[Ideation] 기능 구현

### ISSUE THREAD

**Issue by seungtaekim-q** [RyanKor/IMDE#1]
사용 빈도가 높은 테이블 또는 DB 에 대해서 관계도 (토폴로지)를 시각적으로 표현해야함.

즉, 사용 빈도가 높은 테이블 또는 DB는 좀 더 크기가 큰 원으로 표기가 되어야하고, 빈도가 낮을 수록 원의 크기가 작아야함.

For frequently used tables or DBs, the relationship diagram (topology) must be expressed visually.

In other words, tables or DBs that are used more frequently should be marked with larger circles, and tables or DBs that are used less frequently should be marked with smaller circles.

**Comment by RyanKor** [comment]
아래 기능이 join 쿼리 기준으로 관계도가 그려져야함.
![image](https://github.com/RyanKor/IMDE/assets/40455392/35d5c24a-b26b-4a72-8bd2-cde5137e57ce)

**Comment by RyanKor** [comment]
우아한 스터디 팀원들 피드백

- FK 기반으로 관계도 그리는 작업이 현업에서는 거의 없음.
- Join 단위로 관계도가 그려져야함.
